### ISSUE TITLE
Home page events e2e tests (small and large card views) + event flow to event description

### ISSUE THREAD

**Issue by AdiMakkar** [gctools-outilsgc/gccollab-frontend#223]
GCcollab Frontend displays event recommendations for a particular user.
The following e2e tests need to be created and using haibun should cover the following:

- [x] #241 - The card, when clicked, the event flow takes the user to the event description. 
- [x] #242 - The card's confirm button option is functional for the small card - confirmation and removal.
- [x] #243 - The card's decline button option is functional for the small card - confirmation and removal.
- [x] #244 -The card's confirm button option is functional for the large card.
- [x] #245 - The card's decline button option is functional for the large card.
- [x] #246 - The card is accessible as prescribed using haibun-axe-accessibility.

**Comment by AdiMakkar** [comment]
#241 - completed 
#246 - completed, ongoing accessibility fixes applied as we go

**Comment by AdiMakkar** [comment]
#244 and #245 left for Sprint 47 to be completed. Looking to close this ticket before April 26th.

**Comment by AdiMakkar** [comment]
will close when #244 and #245 are completed.
